/*
  # Add INSERT Policies to Component Tables

  1. Issue
    - Component tables only have SELECT policies
    - No INSERT policies exist, causing RLS violations
    - Enhanced calculation engine cannot populate component data

  2. Solution
    - Add INSERT policies for authenticated users on all component tables
    - Allow system to populate component breakdowns during validation execution

  3. Tables Modified
    - lcr_hqla_components
    - lcr_outflow_components
    - lcr_inflow_components

  4. Security
    - INSERT allowed for authenticated users (system operations)
    - Data is generated by system, not user input
    - Read access already protected by existing SELECT policies
*/

-- Drop existing policies if they exist (cleanup)
DROP POLICY IF EXISTS "Allow authenticated users to insert LCR HQLA components" ON lcr_hqla_components;
DROP POLICY IF EXISTS "Allow authenticated users to insert LCR outflow components" ON lcr_outflow_components;
DROP POLICY IF EXISTS "Allow authenticated users to insert LCR inflow components" ON lcr_inflow_components;
DROP POLICY IF EXISTS "Allow authenticated users to update LCR HQLA components" ON lcr_hqla_components;
DROP POLICY IF EXISTS "Allow authenticated users to update LCR outflow components" ON lcr_outflow_components;
DROP POLICY IF EXISTS "Allow authenticated users to update LCR inflow components" ON lcr_inflow_components;
DROP POLICY IF EXISTS "Allow authenticated users to delete LCR HQLA components" ON lcr_hqla_components;
DROP POLICY IF EXISTS "Allow authenticated users to delete LCR outflow components" ON lcr_outflow_components;
DROP POLICY IF EXISTS "Allow authenticated users to delete LCR inflow components" ON lcr_inflow_components;

-- Add INSERT policy for LCR HQLA components
CREATE POLICY "Allow authenticated users to insert LCR HQLA components"
  ON lcr_hqla_components
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Add INSERT policy for LCR outflow components
CREATE POLICY "Allow authenticated users to insert LCR outflow components"
  ON lcr_outflow_components
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Add INSERT policy for LCR inflow components
CREATE POLICY "Allow authenticated users to insert LCR inflow components"
  ON lcr_inflow_components
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Add UPDATE policy for LCR HQLA components (in case of recalculation)
CREATE POLICY "Allow authenticated users to update LCR HQLA components"
  ON lcr_hqla_components
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Add UPDATE policy for LCR outflow components (in case of recalculation)
CREATE POLICY "Allow authenticated users to update LCR outflow components"
  ON lcr_outflow_components
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Add UPDATE policy for LCR inflow components (in case of recalculation)
CREATE POLICY "Allow authenticated users to update LCR inflow components"
  ON lcr_inflow_components
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Add DELETE policy for cleanup operations
CREATE POLICY "Allow authenticated users to delete LCR HQLA components"
  ON lcr_hqla_components
  FOR DELETE
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated users to delete LCR outflow components"
  ON lcr_outflow_components
  FOR DELETE
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated users to delete LCR inflow components"
  ON lcr_inflow_components
  FOR DELETE
  TO authenticated
  USING (true);
